import path from 'path'
import Head from 'next/head'
import humanizeString from 'humanize-string'
import { getGalleries, getImages } from '../lib/dynamic'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Gallery(props) {
  const router = useRouter()
  const { galleryName } = router.query

  return (
    <div>
      <Head>
        <title>{galleryName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.outer} style={{columns: props.columns}}>
          { props.galleryItems.map( (item) => (
            <article className={styles.inner} key={item.diskPath}>
              <img
                src={item.diskPath}
                alt={item.title}
                width="180"
                height="180" />
            <h2>{item.title}</h2>
            </article>
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
  const images = await getImages(context.params.galleryName);

  const galleryItems = images.map( diskPath => {
    return {
      diskPath,
      title: humanizeString(path.parse(diskPath).name),
    };
  });

  const obj = {props: {
      columns: 2,
      galleryItems,
      }}
  // console.log(JSON.stringify(obj));
  return obj;
}

export async function getStaticPaths() {
  const obj = await getGalleries(); //todo cleanup obj here
  const paths = obj.galleries.map( g => {
    return g.webPath;
  });

  return { paths: paths, fallback: false };
}