import Head from 'next/head'
import { getGalleries } from '../lib/dynamic'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>A Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.outer}>
          { props.galleries.map( (gallery) => (
            <article className={styles.inner} key={gallery.title}>
              <img
              src={gallery.thumbnail}
              alt={gallery.title}
              width="180"
              height="180" />
            <h2>{gallery.title}</h2>
            </article>
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
  const props = {props: await getGalleries()};
  // console.log(JSON.stringify(props));
  return props;
}